# Generated by Django 4.1.5 on 2023-01-11 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='image',
            field=models.URLField(blank=True, null=True, verbose_name='Url de imagen'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='nb_album',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Número de albumes'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='tracklist',
            field=models.URLField(blank=True, null=True, verbose_name='Url Lista de reproduccion'),
        ),
        migrations.AlterModelTable(
            name='album',
            table='albums',
        ),
        migrations.AlterModelTable(
            name='track',
            table='tracks',
        ),
    ]
